steps:
# Paso 1: Configurar Google Cloud SDK
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'config'
  - 'set'
  - 'project'
  - 'proytest-398113'

# Paso 2: Autenticar Docker con GCR usando gcloud
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'auth'
  - 'configure-docker'

# Paso 3: Compilar la imagen de contenedor con Dockerfile personalizado
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/proytest-398113/pbpf-api-ras:v1.0'
  - '-f'
  - 'Dockerfile'
  - '.'

# Paso 4: Publicar la imagen en Google Container Registry usando gcloud
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'builds'
  - 'submit'
  - '--tag'
  - 'gcr.io/proytest-398113/pbpf-api-ras:v1.0'
  - '.'

# Paso 5: Implementar en Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'api-pf-1'
  - '--image'
  - 'gcr.io/proytest-398113/pbpf-api-ras:v1.0'
  - '--platform'
  - 'managed'
  - '--region'
  - 'southamerica-east1'

# Configuración de disparadores
images:
- 'gcr.io/proytest-398113/pbpf-api-ras:v1.0'





#gcloud builds submit --config=cloudbuild.yaml
